### ISSUE TITLE
no such table: main.classroom_student__old

### ISSUE THREAD

**Issue by itzkou** [sibtc/django-multiple-user-types-example#11]
![image](https://user-images.githubusercontent.com/56657738/80918214-c8492a80-8d5b-11ea-9a72-ae9b04be6b85.png)
This is what happen when I click sign Up button

**Comment by teethgrinder** [comment]
update your pip, django. and sqlite3.. it will handle.

**Comment by Aelmeky** [comment]
to which version should I upgrade the pip, Django. and sqlite3
